group:
  # General
  - files:
      - .github/ISSUE_TEMPLATE/
      - .github/workflows/sync-labels.yml
      - .github/CODEOWNERS
      - .github/labels.yml
      - .github/PULL_REQUEST_TEMPLATE.md
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - LICENSE
      - SECURITY.md
    repos: |
      BeaverHouse/python-script-hub

  # Python
  - files:
      - source: .github/workflows/python
        dest: .github/workflows
    repos: |
      BeaverHouse/python-script-hub
