group:
  # General
  - files:
      - .github/ISSUE_TEMPLATE/
      - .github/workflows/sync-labels.yml
      - .github/CODEOWNERS
      - .github/labels.yml
      - .github/PULL_REQUEST_TEMPLATE.md
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - LICENSE
      - SECURITY.md
    repos: |
      BeaverHouse/python-script-hub
      BeaverHouse/aecheck-data
      BeaverHouse/aecheck-v3
      BeaverHouse/dive-argo-fastapi
      BeaverHouse/dive-argo-fastapi-helm

  # Python
  - files:
      - source: .github/workflows/python
        dest: .github/workflows
    repos: |
      BeaverHouse/python-script-hub
      BeaverHouse/aecheck-data

  # Lint
  - files:
      - source: .github/workflows/yarn-lint
        dest: .github/workflows
    repos: |
      BeaverHouse/aecheck-v3

  # No-lint
  - files:
      - source: .github/workflows/yarn-nolint
        dest: .github/workflows
    repos: |
