group:
  # General
  - files:
      - .github/ISSUE_TEMPLATE/
      - .github/workflows/sync-labels.yml
      - .github/CODEOWNERS
      - .github/labels.yml
      - .github/PULL_REQUEST_TEMPLATE.md
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - LICENSE
      - SECURITY.md
    repos: |
      HU-Lee/anotherdungeon
      HU-Lee/aecheck-v2
      HU-Lee/LeetCode
      HU-Lee/BOJ

  # Python
  - files:
      - source: .github/workflows/python
        dest: .github/workflows
    repos: |

  # Lint
  - files:
      - source: .github/workflows/yarn-lint
        dest: .github/workflows
    repos: |
