name: Sync template files (Organization)

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT_ORGANIZATION }}
          CONFIG_PATH: .github/sync-organization.yml
          PR_LABELS: false
          ASSIGNEES: HU-Lee
