name: Sync template files (Personal)

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT_PERSONAL }}
          CONFIG_PATH: .github/sync-personal.yml
          PR_LABELS: false
          ASSIGNEES: HU-Lee
